### PR TITLE
Fix no display the row when no value

### PR DESCRIPTION
**Pull request by ryanfox1985**
No display the row when the value is undefined or empty.

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for this! Are you happy for this to be included under the MIT license?

Also, I don't quite understand what it is trying to fix - the display looks correct to me when there are no rows in the result set - [see this example](https://datatables.net/extensions/rowgroup/examples/initialisation/simple.html).

**Comment by ryanfox1985** [comment]
It's ok MIT license.

I can write an example of case of use, in this case I group by Trip:

| Name | Trip |
|---|---|
| Person1 | A |
| Person2| B |
| People (2) | |
| Person3 | C |
| Person4 | C |

I need to filter empty rows, the current version is inserting always a row like this example:

| Name | Trip |
|---|---|
| | |
| Person1 | A |
| | |
| Person2| B |
| People (2) | |
| Person3 | C |
| Person4 | C |

Regards.

**Comment by DataTables** [comment]
I'm not quite getting it I'm afraid. Here is a live test case: http://live.datatables.net/vigaruke/1/edit .

There is one row which doesn't have a value. But that is still a valid group - I think this it should have a renderer which states that.

**Comment by ryanfox1985** [comment]
Hi,

check the body, you have a empty line. [Screenshot](https://www.dropbox.com/s/9cqsbsj85la95rt/Screenshot%202017-09-12%2017.27.34.png?dl=0)
The `Garrett Winters` has a empty row before (First line).

```html
<tbody>         
        <tr class="group group-start"><td colspan="6"></td></tr><tr role="row" class="odd">
            <td>Garrett Winters</td>
            <td>Director</td>
            <td class="sorting_1"></td>
            <td>63</td>
            <td>2011/07/25</td>
            <td>$5,300</td>
          </tr><tr class="group group-start"><td colspan="6">Edinburgh</td></tr><tr role="row" class="even">
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td class="sorting_1">Edinburgh</td>
            <td>61</td>
            <td>2011/04/25</td>
            <td>$3,120</td>
          </tr><tr role="row" class="odd">
            <td>Cedric Kelly</td>
            <td>Javascript Developer</td>
            <td class="sorting_1">Edinburgh</td>
            <td>22</td>
            <td>2012/03/29</td>
            <td>$3,600</td>
          </tr><tr role="row" class="even">
            <td>Jenna Elliott</td>
            <td>Financial Controller</td>
            <td class="sorting_1">Edinburgh</td>
            <td>33</td>
            <td>2008/11/28</td>
            <td>$5,300</td>
          </tr><tr role="row" class="odd">
            <td>Rhona Davidson</td>
            <td>Integration Specialist</td>
            <td class="sorting_1">Edinburgh</td>
            <td>55</td>
            <td>2010/10/14</td>
            <td>$6,730</td>
          </tr><tr role="row" class="even">
            <td>Sonya Frost</td>
            <td>Software Engineer</td>
            <td class="sorting_1">Edinburgh</td>
            <td>23</td>
            <td>2008/12/13</td>
            <td>$3,600</td>
          </tr><tr role="row" class="odd">
            <td>Quinn Flynn</td>
            <td>Financial Controller</td>
            <td class="sorting_1">Edinburgh</td>
            <td>22</td>
            <td>2013/03/03</td>
            <td>$4,200</td>
          </tr><tr role="row" class="even">
            <td>Dai Rios</td>
            <td>System Architect</td>
            <td class="sorting_1">Edinburgh</td>
            <td>35</td>
            <td>2012/09/26</td>
            <td>$4,200</td>
          </tr><tr role="row" class="odd">
            <td>Doris Wilder</td>
            <td>Sales Assistant</td>
            <td class="sorting_1">Edinburgh</td>
            <td>23</td>
            <td>2010/09/20</td>
            <td>$4,965</td>
          </tr><tr role="row" class="even">
            <td>Gavin Joyce</td>
            <td>Developer</td>
            <td class="sorting_1">Edinburgh</td>
            <td>42</td>
            <td>2010/12/22</td>
            <td>$4,525</td>
          </tr></tbody>
```

Regards.

**Comment by DataTables** [comment]
That's what I would expect. The default renderer will use the grouping data point to display in the grouping row. [The `startRender` option](https://datatables.net/reference/option/rowGroup.startRender) can be used to customise what is shown.

**Comment by ryanfox1985** [comment]
Yes, but with the improvement you can decide to add or not this empty row. 
Maybe it was better if only append the row when is not undefined (allow empty String).

In my case the table is bad looking with these empty rows and is not possible to fix it with CSS.

**Comment by DataTables** [comment]
Since this issue was raised, there has been the addition of the `emptyDataGroup` option which is displayed when the data to display it empty. What I've done is to allow that to be given as `null`, which will result in no grouping row being added.

**Pull request closed without merging**
