### PR TITLE
Enable nested grouping and expand / collapse a group

### PR DESCRIPTION
**Pull request by felipefreitasffs**
Enable expand / collapse a group
Enable multiple data point to be used for grouping at a time - support for nested grouping

### CODE REVIEW

**Comment by DataTables** [comment]
Superb - thank you for this. Are you happy for it to be included under the MIT license?

**Comment by felipefreitasffs** [comment]
Yes, for sure, totally

**Comment by DataTables** [comment]
Thanks! I'm going to do a point release of RowGroup - probably later today. Then I'll merge this in the for next major update.

**Comment by DataTables** [comment]
Awesome :). I'll play around with it a bit and update the docs before releasing.

This is a much requested feature - thanks for contributing it back!

**Comment by alanbec** [comment]
[This](https://github.com/DataTables/RowGroup/pull/8#issuecomment-396895638) is fab news, thank you :) No more idea of an ETA I suppose..?

**Comment by DataTables** [comment]
Not yet. I've actually had a few issues with it locally, so I need to look into that before we can do any kind of release.

**Comment by alanbec** [comment]
Thanks for the update, good luck, and I have a table I can test it on sometime if any help.

**Comment by Sergio1C** [comment]
It feature is working now? Any release?

**Comment by DataTables** [comment]
No. I've got the nested groups integrated, but no luck with expand and contract yet.

**Comment by Sergio1C** [comment]
>No. I've got the nested groups integrated, but no luck with expand and contract yet.

I do not quite understand what you mean here. 
But if i try do it on ["nightly"](https://datatables.net/download/nightly), can it work out?``

**Comment by DataTables** [comment]
Yes, the nested groups will work on the nightly. The expand and contract for a group will not.

**Comment by Sergio1C** [comment]
>

[Here ](https://nightly.datatables.net/rowgroup/js/dataTables.rowGroup.js) im not see a new feature, which beind discussed here..

**Comment by DataTables** [comment]
This is the commit: https://github.com/DataTables/RowGroup/commit/6c7a917c10d79d74e3a266e79cb7e3c72c5577fe .

**Comment by JamesHarvey18** [comment]
I know this is a year later, but did the expand and collapse feature ever get added? Thanks!

**Comment by DataTables** [comment]
No - it didn't appear to work fully, so that aspect was never merged in. That an open enhancement that anyone is welcome to pick up and send a PR for if you want to work on it.

**Comment by vip3rousmango** [comment]
Any updates to this? Looking to expand/collapse Grouped Rows as well and would love to see this feature implemented!

**Comment by DataTables** [comment]
When I've got an update, I'll post it here :-). Until then anyone else is welcome to work on it.

**Comment by vip3rousmango** [comment]
> When I've got an update, I'll post it here :-). Until then anyone else is welcome to work on it.

Sounds good!  Thanks for the fast reply.

We've got a use-case that could require me to create this so if I figure this out nicely I'll look into seeing if I can also wrap it up into a PR (need to check if it's okay to release under MIT).

**Comment by MomasVII** [comment]
If anyone requires a quick and dirt solution I found this is quite clean and works well enough...(sorry I don't know how to format well)

`$('.group').click(function() {
        var nextItem = $(this).next();
        while(nextItem.attr('class') != 'group') {
            nextItem.fadeToggle();
            nextItem = nextItem.next();
        }
    });`

**Comment by mariabohorquez** [comment]
Is there any way to apply expand/collapse now?

**Comment by DataTables** [comment]
No sorry. It is not something I've added in yet.

**Comment by mariabohorquez** [comment]
Thanks for the answer, is no biggie. I just wanted to know if someone had found a workaround for it. Thanks for your hard work with the library, I am just starting to use it and it's really easy to use and looks good.

**Pull request merged**
